# Generated by Django 5.1.6 on 2025-05-08 12:40

import plants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sunlight_needs', models.CharField(choices=[('low', 'Low Light'), ('medium', 'Medium Light'), ('high', 'Bright Light')], max_length=20)),
                ('water_needs', models.CharField(choices=[('low', 'Every 2-3 Weeks'), ('medium', 'Weekly'), ('high', '2-3 Times Weekly')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], max_length=20)),
                ('location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Indoor/Outdoor')], max_length=20)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=plants.models.plant_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunlight', models.CharField(choices=[('low', 'Low Light'), ('medium', 'Medium Light'), ('high', 'Bright Light')], max_length=20)),
                ('water', models.CharField(choices=[('low', 'Every 2-3 Weeks'), ('medium', 'Weekly'), ('high', '2-3 Times Weekly')], max_length=20)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Indoor/Outdoor')], max_length=20)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
