# Generated by Django 5.1.6 on 2025-05-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/HP X-360 1030 G2/plant_suggester2/static/images/default-plant.jpeg'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='experience',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='sunlight',
            field=models.CharField(choices=[('low', 'Low Light'), ('medium', 'Medium Light'), ('high', 'Bright Light')], max_length=20, verbose_name='Sunlight Available'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='water',
            field=models.CharField(choices=[('low', 'Every 2-3 Weeks'), ('medium', 'Weekly'), ('high', '2-3 Times Weekly')], max_length=20, verbose_name='Watering Capacity'),
        ),
    ]
